### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'bins'

### ISSUE THREAD

**Issue by RuoyuChen10** [ArminBaz/UTK-Face#2]
Hi, when I try `Sandbox.ipynb`, it occurs error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[5], line 27
     21 test_transform = transforms.Compose([
     22     transforms.ToTensor(),
     23     transforms.Normalize((0.49,), (0.23,))
     24 ])
     26 # Construct the custom pytorch datasets
---> 27 train_set = UTKDataset(train_dataFrame, transform=train_transform)
     28 test_set = UTKDataset(test_dataFrame, transform=test_transform)
     30 # Load the datasets into dataloaders

File [~/](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a224c5346227d.vscode-resource.vscode-cdn.net/home/lsf/%E6%A1%8C%E9%9D%A2/UTK-Face/~/)desktop[/UTK-Face/src/CustomUTK.py:29](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a224c5346227d.vscode-resource.vscode-cdn.net/UTK-Face/src/CustomUTK.py:29), in UTKDataset.__init__(self, dataFrame, transform)
     26 self.data = arr
     28 # get the age, gender, and ethnicity label arrays
---> 29 self.age_label = np.array(dataFrame.bins[:])         # Note : Changed dataFrame.age to dataFrame.bins
     30 self.gender_label = np.array(dataFrame.gender[:])
     31 self.eth_label = np.array(dataFrame.ethnicity[:])

File [~/anaconda3/envs/utk-face/lib/python3.8/site-packages/pandas/core/generic.py:5902](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a224c5346227d.vscode-resource.vscode-cdn.net/home/lsf/%E6%A1%8C%E9%9D%A2/UTK-Face/~/anaconda3/envs/utk-face/lib/python3.8/site-packages/pandas/core/generic.py:5902), in NDFrame.__getattr__(self, name)
   5895 if (
   5896     name not in self._internal_names_set
   5897     and name not in self._metadata
   5898     and name not in self._accessors
   5899     and self._info_axis._can_hold_identifiers_and_holds_name(name)
...
   5900 ):
   5901     return self[name]
-> 5902 return object.__getattribute__(self, name)

AttributeError: 'DataFrame' object has no attribute 'bins'
``` 

This is because when I run the command:

```python
# Construct the custom pytorch datasets
train_set = UTKDataset(train_dataFrame, transform=train_transform)
```

Can you help fix the bug?

**Comment by arminbazza** [comment]
Hey, thanks for your interest in this repo. Unfortunately, `SandBox.ipynb` is horribly out of date as it was just a place for me to mess around and test different things. If you'd like the most up to date notebook you can checkout `colab/TrainTridentMain.ipynb`. I'm sure you can still run it within an IDE that supports jupyter.

To answer your question. The bug is because `SandBox.ipynb` doesn't include this code:
```python
# Construct age bins
age_bins = [0,10,15,20,25,30,40,50,60,120]
age_labels = [0, 1, 2, 3, 4, 5, 6, 7, 8]
dataFrame['bins'] = pd.cut(dataFrame.age, bins=age_bins, labels=age_labels)
```
What this does is construct age bins so I can treat age as a classification problem rather than a regression problem.

<br> 

Note that you also need to add this code in the notebook too:
```python
class_nums = {'age_num':len(dataFrame['bins'].unique()), 'eth_num':len(dataFrame['ethnicity'].unique()),
              'gen_num':len(dataFrame['gender'].unique())}
```

<br>

Again, `SandBox.ipynb` is out of date and I will get around to updating it. In the meantime `colab/TrainTridentMain.ipynb` should be better suited for your needs.

Thanks!

**Comment by RuoyuChen10** [comment]
> Hey, thanks for your interest in this repo. Unfortunately, `SandBox.ipynb` is horribly out of date as it was just a place for me to mess around and test different things. If you'd like the most up to date notebook you can checkout `colab/TrainTridentMain.ipynb`. I'm sure you can still run it within an IDE that supports jupyter.
> 
> To answer your question. The bug is because `SandBox.ipynb` doesn't include this code:
> 
> ```python
> # Construct age bins
> age_bins = [0,10,15,20,25,30,40,50,60,120]
> age_labels = [0, 1, 2, 3, 4, 5, 6, 7, 8]
> dataFrame['bins'] = pd.cut(dataFrame.age, bins=age_bins, labels=age_labels)
> ```
> 
> What this does is construct age bins so I can treat age as a classification problem rather than a regression problem.
> 
> 
> Note that you also need to add this code in the notebook too:
> 
> ```python
> class_nums = {'age_num':len(dataFrame['bins'].unique()), 'eth_num':len(dataFrame['ethnicity'].unique()),
>               'gen_num':len(dataFrame['gender'].unique())}
> ```
> 
> 
> Again, `SandBox.ipynb` is out of date and I will get around to updating it. In the meantime `colab/TrainTridentMain.ipynb` should be better suited for your needs.
> 
> Thanks!

Thank you very much for your reply. Now I have solved the problem, thank you.
